language: python

env:
  global:
    secure: ENyjVN6N1b30TCfz7jM8c0bQx7q9hiOyONbryphy+uSJbrNlo1+cuk6ct/dQdJ9sAPx6jWDYah/5CrSSZ8gqo7X58gSiNJZ72pgFX07Vfk8aSWH7SMsL07wm+fB5tiyOxRnEA9HrshvgpU+Ky/Gwzf7K3z4mA84ejtXFWTVdCd7SePVupWolibDi2Ca5Ggkp/0DTI1HcNWOhflqWmOMizb1O7DaN2NEsuMmdcJOteyPAPzLMMh1+O6dUadrgzbVIcglIXi6gx4FSWPKrqrzYRJHfi6A2j6fmZEB4HFAJ/4FdXU42NwwmCZbKhIWBPwzLJ+o8AEQgRtWRRqkLjuPnOUOTtY5pHLvABkQ0MJaiJzezIMtxh7Lz2Lp827SidjaawEjZOs0JA0+/NuibBbsijVLBs6W9ezG1PUHZovWX52r5ningcFvyCjW68DE9EGDD7V12yfE0OBYpiVIXlFyUnDtG9fzs4/8E65jm6VI9Hv+9T4i6X+aMTLmjcp0YrI3GK6PfL1vJ7NwkM1MWaZ37SIEST+Ex9iiqVVJt5pvCSqbuYdm4qTzKyQgyn7FR3v1fk857nA0FRpP4W0AwGXIn+5SAZtdYQXOTnyj+rYH7ocoHRu5/Ixivpy3CoJ1q4TTUyh7o6bWQUe7XRpZuRQ/k+nHF8jin+9wLrjH+eCI1/IU=


matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
#    - sudo: required
#      services:
#        - docker
#      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
#           PRE_CMD=linux32
#           PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

before_install:
  - chmod +x .ci/travis_build_wheels.sh

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.ci/travis_build_wheels.sh
  - ls wheelhouse/

before_deploy:
  - cd wheelhouse

deploy:
  skip_cleanup: true
  provider: script
  script: .ci/travis_deploy.sh
  on:
    tags: true
#  provider: pypi
#  user: DomDF
#  distributions: sdist bdist_wheel
#  skip_existing: true
#  password:
#    secure: FosMnyDTf6nzTx4kk/x8DLwxtgMBlK/ET8aRtcgplEwagCBSUIpCeMrTj26LF4gDHI5/EtNoKTGD6KtlCT9OOlyP+MIhSb670+6iaprGoEF91j72SgqjPHUsmsxMj1wgwBjrnut7COy/+lTlLKsH9jmylUkKirQwLsjcwjQMyhsvtmGBQfxYqqVh+qJbv8YnGCXuqvpqy4Ga66SRiOlHaK38zMo2hwJxV32DagIq0LjktA7sOR2CLmtBxKV7S4Ac2CGhG6BqMIdt/r+XD5IijZLXINAfRMfQ2VWwPozY68tfHiqnJ6zBpW6vccmJo386h4vAZg2SZtsn6UCRh3dAsgrAk7r3BjhqA3XVj9CeHk76TrAUUrFu9EuxPVQNwsZ4iawrn2gSD4KONb4zUIFlDErRmZFYaARrohhnEp32sdtLYgfKXO/GlWjmtUS6TefcJFYKcw5ZJHP4WEn+G09ZLJuMm86+YStFyF1BBvoOeXQ8wWjZS4wf5+0muhPGS+iJ9x4lYhwNxQvxD5Y9T7Z8MfZAN+V9yPuIsI/B+Qo+nJFfKkNJnvBy6swukAVXHYKHIX8qDBVBYzUSBH3eFrHMDhH3UxkmffG6EaiX6PeE3xPbAcZZjnbaMECJS1cgNZeU4W7Q38lYUvtMtMK/XJttoozJz70nO2Ctjw0tol4qSCc=
#  file:
#    - "pyms_nist_search-${VERSION}-${PY36}-${PLAT}.whl"
#    - "pyms_nist_search-${VERSION}-${PY37}-${PLAT}.whl"
