language: python
dist: xenial
python:
- '3.6'
- '3.7'
- 3.8-dev
install:
- choco install visualstudio2019buildtools
os: windows
#deploy:
#  provider: pypi
#  user: DomDF
#  on:
#    tags: true
#    python: '3.6'
#  distributions: sdist bdist_wheel
#  skip_existing: true