language: python
dist: xenial
cache: pip
python:
  - '3.6'

stages:
  - mypy
  - build

jobs:
  include:
    - stage: mypy
      python: "3.6"
      install:
        - pip install pip  --upgrade
        - pip install tox tox-travis
      script:
        - tox -e mypy

    - stage: build
      python: "3.6"
      install:
        - pip install pip  --upgrade
        - pip install tox tox-travis
      script:
        - tox -e build
