version: 1.0.{build}
clone_depth: 50  # The same depth Travis has
image: Visual Studio 2019

environment:
  matrix:
#    # Python36
#    - TOXENV: "py36"
#      PYTHON: "C:\\Python36"
#      TOX_APPVEYOR_X64: 0
    # Python37
    - TOXENV: "py37"
      PYTHON: "C:\\Python37"
      TOX_APPVEYOR_X64: 0
    # Python38
    - TOXENV: "py38"
      PYTHON: "C:\\Python38"
      TOX_APPVEYOR_X64: 0
    # Python39
    - TOXENV: "py39"
      PYTHON: "C:\\Python39"
      TOX_APPVEYOR_X64: 0
#    # Python310
#    - TOXENV: "py310"
#      PYTHON: "C:\\Python310"
#      TOX_APPVEYOR_X64: 0
#    # Python36-x64
#    - TOXENV: "py36"
#      PYTHON: "C:\\Python36-x64"
#      TOX_APPVEYOR_X64: 1
    # Python37-x64
    - TOXENV: "py37"
      PYTHON: "C:\\Python37-x64"
      TOX_APPVEYOR_X64: 1
    # Python38-x64
    - TOXENV: "py38"
      PYTHON: "C:\\Python38-x64"
      TOX_APPVEYOR_X64: 1
    # Python39-x64
    - TOXENV: "py39"
      PYTHON: "C:\\Python39-x64"
      TOX_APPVEYOR_X64: 1
    # Python310-x64
    - TOXENV: "py310"
      PYTHON: "C:\\Python310-x64"
      TOX_APPVEYOR_X64: 1
    # Python311-x64
    - TOXENV: "py311"
      PYTHON: "C:\\Python311-x64"
      TOX_APPVEYOR_X64: 1
    # Python312-x64
    - TOXENV: "py312"
      PYTHON: "C:\\Python312-x64"
      TOX_APPVEYOR_X64: 1

  pypi_token:
    secure: T7c6dwug8be6NlOGpL44ftGSw9RgNw/HsHNb7xdbhzX1iZ+DbKznSIzxHdIVxSgxx0BqEkLR56CtXOU0AgOmpylc9/yysdd9R8ZOjwobJuCK7Tb+Q+/T+Cvby2fZmuvqAIxwBBS/j2337iFdbTIOR9JN6emUuv3Cmc2Ufzl6bzi7kuUjXo9OmRp87gHq/XCDh1zHGnp0VVMmPOzMORa/+byOY21qh0PW0m3giBdhY4xFm32wGB7GRX1fIx98ttGrC5lMU3k1PXs+RK+bJ/OcamAhRnRG9h6VfIkbNwniV5Y=

  PIP_PREFER_BINARY: 1

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel Cython tox~=3.0 tox-appveyor build"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

after_test:
  - ".ci\\build.cmd %PYTHON%\\python.exe -m build"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*.whl
    name: wheels

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying to PyPI...")
        &"${Env:PYTHON}/python.exe" -m pip install twine
        &"${Env:PYTHON}/python.exe" -m twine upload -u __token__ -p ${Env:pypi_token} --skip-existing dist/*.whl
      } else {
        Write-Output "No tag for deployment"
      }
