# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Artefact Cleaner
on:
  schedule:
  - cron: 0 9 1 * *
jobs:
  Clean:
    runs-on: ubuntu-latest
    steps:
    - name: cleanup
      uses: glassechidna/artifact-cleaner@v2
      with:
        minimumAge: 1000000.0
