# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: mypy

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  Run:
    name: "mypy / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.6"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox

      - name: "Run mypy"
        run: "python -m tox -e mypy"
