# This file is managed by `repo_helper`. Don't edit it directly
---

name: "GitHub Releases"
on:
  push:
  schedule:
    - cron: 0 12 * * 2,4,6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: domdfcoding/octocheese@master
        with:
          pypi_name: "pyms-nist-search"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
