---
name: Windows Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "windows-2019"
    env:
      USING_COVERAGE: '3.6,3.7,3.8'

    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.6","3.7","3.8"]


    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"
      - name: Setup Python 🐍
        uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox tox-gh-actions

      - name: "Run Tests for Python ${{ matrix.python-version }}"
        run: "python -m tox"
